#docker compose for local development

version: '3.6'

services:

  #####################################################################################
  registry:
  #####################################################################################
    container_name: registry
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - registry:/var/lib/registry
      - ./registry-config/simple.yml:/etc/docker/registry/config.yml


  #####################################################################################
  registry-ui:
  #####################################################################################
    container_name: registry-ui
    image: parabuzzle/craneoperator:latest
    ports:
      - "8086:80"
    environment:
      - REGISTRY_HOST=registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - USERNAME=admin
      - PASSWORD=mypassword
      - REGISTRY_ALLOW_DELETE=true
    restart: always
    depends_on:
      - registry


  #####################################################################################
  registry-ui2:
  #####################################################################################
    image: joxit/docker-registry-ui:latest
    ports:
      - 8087:80
    environment:
      - REGISTRY_TITLE=perit.local
      - REGISTRY_URL=http://docker-registry:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    depends_on:
      - registry


volumes:
  registry:
