#-----------------------------------------------------------------------------------------------------------------------
# ServiceAccount
#-----------------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
